### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by oalam** [blackberry/KaBoom#1]
I would like to use this project but I'am not able to build it from maven install due to com.blackberry.common

is this project still alive ?

[ERROR] Failed to execute goal on project kaboom: Could not resolve dependencies for project com.blackberry.kaboom:kaboom:jar:0.7.0: Failed to collect dependencies at com.blackberry.common:common:jar:0.0.4: Failed to read artifact descriptor for com.blackberry.common:common:jar:0.0.4: Could not transfer artifact com.blackberry.common:common:pom:0.0.4 from/to jitpack.io (https://jitpack.io): Failed to transfer file: https://jitpack.io/com/blackberry/common/common/0.0.4/common-0.0.4.pom. Return code is: 400 , ReasonPhrase:Expecting: /com/github/user/repo[/module]/version/repo-version.pom. -> [Help 1]

**Comment by timwindsor** [comment]
@ariens Are you taking a look at this?

**Comment by oalam** [comment]
Thanks for your reply

with your forked repo I can now build Krackle but for Kaboom the dependency on com.blackberry.common is still missing.

I didn’t find any trace of it on the web. Any idea ?

thanks for your help

**Comment by ariens** [comment]
Please note that Krackle, KaBoom, and Klogger have all have fairly major updates and those updates have now been pushed to Github.  Here's a summary:

KaBoom 0.7.2 (dev branch): https://github.com/ariens/KaBoom (Changes: https://github.com/ariens/KaBoom/blob/dev/docs/change-log.txt)
Krackle 0.7.10 (dev branch): https://github.com/ariens/Krackle (Changes:  https://github.com/ariens/Krackle/blob/dev/docs/change-log.txt)
Klogger 0.7.9 (dev branch): https://github.com/ariens/Klogger (Changes: https://github.com/ariens/Klogger/blob/dev/docs/change-log.txt)
Common-Utils 0.0.4 (master branch): https://github.com/ariens/BB-BigData-Common-Utils 
Test-Utils 0.0.1 (master branch) https://github.com/ariens/BB-BigData-Common-TestUtils

These project version are all currently residing under my personal space (not BlackBerry) for the time being until they can be pulled into the BB org's space accordingly.

I'm actively working on pushing these projects artifacts to Maven Central, however in the meantime, building each of these locally will provide all the artifacts for a deploying a fully functional high performance ingest/consumer stack around Kafka 0.8.1.1.
